// Courses
export const GET_COURSES = 'GET_COURSES'

// Articles
export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLES_PUBLISHED_BY_YEAR = 'GET_ARTICLES_PUBLISHED_BY_YEAR'
export const GET_ARTICLES_WITH_MORE_DOWNLOADS = 'GET_ARTICLES_WITH_MORE_DOWNLOADS'
export const GET_ARTICLES_WITH_MORE_VIEWS = 'GET_ARTICLES_WITH_MORE_VIEWS'

// Tags

// UI
export const SET_LOADING = 'SET_LOADING'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
