// Courses
export const GET_COURSES_WITH_MORE_VIEWS = 'GET_COURSES_WITH_MORE_VIEWS'
export const GET_COURSES_PUBLISHED_BY_YEAR = 'GET_COURSES_PUBLISHED_BY_YEAR'

// Articles
export const GET_ARTICLES_PUBLISHED_BY_YEAR = 'GET_ARTICLES_PUBLISHED_BY_YEAR'
export const GET_ARTICLES_AND_DOWNLOADS = 'GET_ARTICLES_AND_DOWNLOADS'
export const GET_ARTICLES_AND_VIEWS = 'GET_ARTICLES_AND_VIEWS'
export const GET_ARTICLES_WITH_MORE_VIEWS = 'GET_ARTICLES_WITH_MORE_VIEWS'
export const GET_ARTICLES_WITH_MORE_DOWNLOADS = 'GET_ARTICLES_WITH_MORE_DOWNLOADS'

// Users
export const GET_USERS_WITH_MORE_PUBLISHED = 'GET_USERS_WITH_MORE_PUBLISHED'
// export const GET_USERS_WITH_MORE_PUBLISHED_IN_COURSE = 'GET_USERS_WITH_MORE_PUBLISHED_IN_COURSE'
// export const GET_USERS_WITH_MORE_PUBLISHED_IN_YEAR = 'GET_USERS_WITH_MORE_PUBLISHED_IN_YEAR'
export const GET_USERS_MORE_VISUALIZED = 'GET_USERS_MORE_VISUALIZED'

// Tags
export const GET_TAGS_MORE_USED_IN_ARTICLES = 'GET_TAGS_MORE_USED_IN_ARTICLES'

// Search
export const UPDATE_CHART_TITLES = 'UPDATE_CHART_TITLES'
export const GET_ARTICLES_SEARCH = 'GET_ARTICLES_SEARCH'
export const GET_COURSES_SEARCH = 'GET_COURSES_SEARCH'
export const GET_USERS_SEARCH = 'GET_USERS_SEARCH'

// UI
export const SET_LOADING = 'SET_LOADING'
export const REMOVE_LOADING = 'REMOVE_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const NO_RESULTS = 'NO_RESULTS'
